eatler-login-otp-master/Eatler/urls.py
from django.conf.urls import url, include
from django.urls import path
from django.contrib import admin
from accounts.api import urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('accounts.urls')),
    path('account_api/', include(urls)),
]

eatler-login-otp-master/accounts/api/urls.py
from django.urls import path
from accounts.api import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    # path('hello/', views.HelloView.as_view(), name='hello'),
    path('generate/',views.otp.as_view(), name="generate"),
    path('register/',views.register.as_view(), name="register"),
    path('login/',views.login.as_view(),name="login"),

    # path('validate/', ValidateOTP.as_view(), name="validate"),
]

# phone number ->otp jayega->otp verify->token return (Login)

# phone_number/full name/country_code/ ->otp bhejega->otp verify -> databases me save karna

eatler-login-otp-master/accounts/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.contrib.auth import logout
from .views import ( RegisterView, DashboardView,
                    LoginView, PhoneVerificationView,
                    IndexView,view1)
from django.contrib.auth import views as auth_views

app_name='accounts'
urlpatterns = [
    url(r'^$', IndexView.as_view(), name='index_page'),
    url(r'^register/$', RegisterView.as_view(), name="register_url"),
    url(r'^login/$',LoginView, name="login_url"),
    url(r'^verify/$', PhoneVerificationView, name="phone_verification_url"),
    url(r'^dashboard/$', DashboardView.as_view(), name="dashboard_url"),
    url(r'^xyz/$',LoginView,name="LoginView"),
    url(r'^logout/$',auth_views.LogoutView.as_view(),name='logout'),
]

eatler-login-otp-master/accounts/models.py
from datetime import date
from django.db import models
from django.contrib.auth.models import PermissionsMixin, AbstractUser
from django.contrib.auth.base_user import AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from django.contrib.auth.models import UserManager
from django.conf import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from rest_framework.authtoken.models import Token

class UserManager(UserManager):
    use_in_migrations = True

    def _create_user(self, phone_number,password=None, **extra_fields):   #remove password

        if not phone_number:
            raise ValueError('The given phone number must be set')
        user = self.model(phone_number=phone_number,password=password, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone_number, **extra_fields):   # password=None
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(phone_number,password, **extra_fields)

    def create_superuser(self, phone_number,password=None, **extra_fields):    #remove password
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone_number,password,  **extra_fields)   #remove password


class User(AbstractBaseUser, PermissionsMixin):
    # username = models.CharField(_('username'), max_length=130, unique=True)
    full_name = models.CharField(_('full name'), max_length=130, blank=True)
    is_staff = models.BooleanField(_('is_staff'), default=False)
    is_active = models.BooleanField(_('is_active'), default=True)
    date_joined = models.DateField(_("date_joined"), default=date.today)
    # phone_number_verified = models.BooleanField(default=False)
    # change_pw = models.BooleanField(default=True)
    phone_number = models.IntegerField(unique=True)
    country_code = models.IntegerField()
    # two_factor_auth = models.BooleanField(default=False)
    password=models.CharField(blank=True,max_length=100)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['full_name', 'country_code']

    class Meta:
        # ordering = ('username',)
        verbose_name = _('user')
        verbose_name_plural = _('users')

    

    def get_short_name(self):
        """
        Returns the display name.
        If full name is present then return full name as display name
        else return username.
        """
        if self.full_name != '':
            return self.full_name
        else:
            return self.phone_number


    def __str__(self):

        return self.full_name

    def get_model_fields(self):
        return self._meta.fields

@receiver(post_save,sender=settings.AUTH_USER_MODEL)
def create_auth_token(sender,instance=None,created=False,**kwargs):
    if created:
        Token.objects.create(user=instance)

eatler-login-otp-master/accounts/forms.py
from django import forms
from django.conf import settings
from django.utils.translation import ugettext as _
# from django.contrib.auth.password_validation import validate_password
from django.contrib.auth import authenticate

from .models import User


class RegisterForm(forms.ModelForm):

    # phone_number = forms.IntegerField(required=True)
    # password1 = forms.CharField(widget=forms.PasswordInput())
    # password2 = forms.CharField(widget=forms.PasswordInput())
    # country_code = forms.IntegerField()

    # MIN_LENGTH = 4

    class Meta:
        model = User
        fields = ['country_code','phone_number',
                  'full_name' ]  # 'username' 'password1', 'password2',

    # def clean_username(self):
    #     username = self.data.get('username')
    #     return username

    # def clean_password1(self):
    #     password = self.data.get('password1')
    #     validate_password(password)
    #     if password != self.data.get('password2'):
    #         raise forms.ValidationError(_("Passwords do not match"))
    #     return password

    def clean_phone_number(self):
        phone_number = self.data.get('phone_number')
        if User.objects.filter(phone_number=phone_number).exists():
            raise forms.ValidationError(
                _("Another user with this phone number already exists"))
        return phone_number

    def save(self, *args, **kwargs):
        user = super(RegisterForm, self).save(*args, **kwargs)
        # user.set_password(self.cleaned_data['password1'])
        print('Saving user with country_code', user.country_code)
        user.save()
        return user


class PhoneVerificationForm(forms.Form):
    one_time_password = forms.IntegerField()

    class Meta:
        fields = ['one_time_password',]



class LoginForm(forms.Form):
    # username = forms.CharField()
    # phone_number=forms.IntegerField(unique=True)
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields =  ['phone_number']             #['username','password']

    # def clean(self):
    #     # username = self.cleaned_data.get('username')
    #     phone_number=self.cleaned_data.get('phone_number')
    #     # password = self.cleaned_data.get('password')
    #     # user = authenticate(username=phone_number, password=password)
    #
    #     if not user:
    #         raise forms.ValidationError("Sorry, that login was invalid. Please try again.")
    #     return self.cleaned_data
    #
    # def login(self, request):
    #     username = self.cleaned_data.get('username')
    #     password = self.cleaned_data.get('password')
    #     user = authenticate(username=username, password=password)
    #     return user

    def save(self, *args, **kwargs):
        user = super(LoginForm, self).save(*args, **kwargs)
        # user.set_password(self.cleaned_data['password1'])
        print('Saving user with country_code', user.phone_number)
        user.save()
        return user

eatler-login-otp-master/accounts/api/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from django.conf import settings
from rest_framework import status
from rest_framework.generics import CreateAPIView
from rest_framework.response import Response
from accounts.models import User
from django.shortcuts import get_object_or_404
from accounts.api.serializers import (
    RegistrationSerializer,OTPSerializer,LoginSerializer
)
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from accounts.authy_api import send_verfication_code,verify_sent_code
from rest_framework.authtoken.models import Token
import json





class register(CreateAPIView):
    serializer_class = RegistrationSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(
            data=request.data,
        )
        if serializer.is_valid():
            fullname = serializer.validated_data['full_name']
            phonenumber = serializer.validated_data['phone_number']
            countrycode = serializer.validated_data['country_code']
            otp = serializer.validated_data['otp']
            already = User.objects.filter(phone_number=phonenumber)
            if already:
                dict = { 'status':'user already exists'}
                return Response(dict)
            user = { 'phone_number': phonenumber, 'country_code': countrycode, 'full_name': fullname}
            response = verify_sent_code(otp, user)
            data = json.loads(response.text)
            if data['success'] == True:

                account=serializer.save()
                token = Token.objects.get(user=account).key
                dict ={ 'user': user, 'status': 'registered','token':token,'success':'True'}
                return Response(dict)
            else:
                dict ={ 'user': user, 'status': 'unregistered','success':'False' }
                return Response(dict)


class otp(CreateAPIView):
    serializer_class = OTPSerializer

    def post(self, request, format=None):
        serializer = self.serializer_class(
            data=request.data,
        )
        if serializer.is_valid():
            phonenumber = serializer.validated_data['phone_number']
            countrycode = serializer.validated_data['country_code']
            user = { 'phone_number': phonenumber, 'country_code': countrycode }
            response = send_verfication_code(user)
            data = json.loads(response.text)

            if data['success'] == False:
                dict = {'status': 'OTP not send! Try Again', 'success': 'False'}
                return Response(dict)
            else:
                dict = { 'status': 'OTP Sent successfully', 'phone_number': phonenumber, 'success': 'True'}
                return Response(dict)
        else:
            data = serializer.errors
            return Response(data)


class login(CreateAPIView):
    serializer_class = LoginSerializer

    def post(self,request,format=None):
        serializer = self.serializer_class(
            data=request.data,
        )
        if serializer.is_valid():
            phonenumber = serializer.validated_data['phone_number']
            countrycode = serializer.validated_data['country_code']
            user = { 'phone_number': phonenumber, 'country_code': countrycode }
            otp = serializer.validated_data['otp']
            response = verify_sent_code(otp, user)
            data = json.loads(response.text)
            if data['success'] == True:
                userob=get_object_or_404(User,phone_number=phonenumber)
                if userob:
                     token, _ = Token.objects.get_or_create(user=userob)
                     return Response({'user':user,'token': token.key,'status':'Token Generated','success':'True'})


                return Response({'status':'User does not exist','sucess':'False'})
            else:
                return Response({'status':'OTP entered is not valid','success':'False'})

eatler-login-otp-master/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
  integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="3">DJANGO</a></li>
          <li><a class="navbar-link" href="3">Admin</a></li>
          <li><a class="navbar-link" href="#">Register</a></li>
          {% if user.is_authenticated %}
                  <a class="nav-link" href="/logout">Logout</a>
                {% else %}
                  <a class="nav-link" href="/login">Login</a>
          {% endif %}

        </ul>

      </div>
    </nav>
    <div class="container">
  {% block body_block %}
  {% endblock %}
  </div>
  </body>
</html>

eatler-login-otp-master/accounts/templates/accounts/dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="/static/css/bootstrap.min.css">
  <title>Dashboard</title>
</head>
<body>
  <div class="jumbotron">
    <div class="container">
      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
    <h1>Yahoo logged in!</h1>
    <br><br>
    <div class="table-responsive">
      <table class="table">
        <tr>
          <td>
            Name : {{user.full_name}}
            <br>
            Phone : +{{user.country_code}} {{user.phone_number}}
            <!-- <br>
            Username : {{user.get_username}}
            <br> -->
          </td>
          <td>
          <!-- Account Verified: {{user.phone_number_verified}} -->
          <br>
          <!-- <form action="" method="post">
            {% csrf_token %}
            Two Factor Authentication:
              {%if user.two_factor_auth %}
              <button type="submit" class="btn btn-success" name="two_factor_auth">
                ENABLED
              {%else%}
              <button type="submit" class="btn btn-danger" name="two_factor_auth">
                DISABLED
              {%endif%}
            </button>
            Click to toggle.
          </form> -->

        </tr>
      </table>

</div>
    <a href="/logout"  class="btn btn-danger">Logout</a>
  </div>
  </div>
  <script src="/static/js/jquery.min.js" charset="utf-8"></script>
  <script src="/static/js/bootstrap.min.js" charset="utf-8"></script></body>
</html>

eatler-login-otp-master/accounts/templates/accounts/index.html
{% extends "accounts/base.html" %}
{% load static %}
{% block body_block %}
<a href="/register" class="btn btn-default">Register</a>
<a href="/login" class="btn btn-info">Login</a>
{%endblock%}

eatler-login-otp-master/accounts/templates/accounts/login.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eatler</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:600&display=swap" rel="stylesheet">
  	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
  	<meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <!-- <link href="/static/css/bootstrap.min.css" rel="stylesheet"> -->


    </head>

  <body>

  <div class="container">
    <div class="img">
      <img src="{% static 'images/food1.jpg' %}">
    </div>
    <div class="login-content">
      <form method="POST"  action="" autocomplete="off">
        {% csrf_token %}
        <img src="{% static 'images/avatar.svg' %}">
        <h3 class="title" >Login to Continue</h2>
          <br>
              <div class="input-div one" >
                  <div class="i">

                     <i class="fas fa-user"></i>
                  </div>

                  <div class="div">
                      <h5>Phone Number</h5>
                       <input id="myInput" class="input"  maxlength="10" name="phone_number" type="text" required />
                       {{ form.phone_number.errors }}
                </div>
              </div>


           <input type="submit" class="btn" value="Login" >

           <h3> Don't have an account?</h3>
         <div>
           <a   style="text-align:center" href="{% url "accounts:register_url" %}"><h4>Register</h4></a>
         </div>


            </form>

            <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        </div>
    </div>


  </body>
</html>

eatler-login-otp-master/accounts/templates/accounts/phone_confirm.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Eatler</title>

    <link rel="stylesheet" href="{% static 'css/phone_confirm.css'%}">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">

    </head>

  <body>
<div class="jumbotron">

    <div class="container">

      <div class="col-sm-6 col-sm-offset-3">


      {% block content %}

      {% if messages %}
      <div id="messages">
        {% for message in messages %}
        <div class="alert alert-dismissible alert-info"
             role="alert">
          <button type="button" class="close" data-dismiss="alert"
                  aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
          {{ message|escape }}
        </div>
        {% endfor %}
      </div>
      {% endif %}
      <div class="container">
        <div class="img">
          <img src="{% static 'images/food1.jpg' %}">
        </div>


        <div class="login-content">



      <form class="form-inline" id="login_form" method="POST" action="/verify/" >
        {% csrf_token %}
        <img src="{% static 'images/avatar.svg' %}">
        <h3 class="title">Confirm your phone number  {{user.phone_number}}</h3>
        <br>

        <!-- <input type='hidden' name='username' value='{{user.username}}' />

        <div class="form-group{% if form.one_time_password.errors %} has-error{% endif %}">
          <label class="control-label" for="id_one_time_password">One Time Password</label>
          <div class="input-group input-group-lg">

          </div>
          <input class="form-control input-lg" id="id_one_time_password" name="one_time_password" type="password" required />
          <div class="error-block">{{ form.one_time_password.errors }}</div>
        </div> -->
        <input type='hidden' name='phone_number' value='{{user.phone_number}}' />

        <div class="form-group{% if form.one_time_password.errors %} has-error{% endif %}">
          <label class="control-label" for="id_one_time_password">One Time Password</label>
          <div class="input-group input-group-lg">

          </div>
          <input class="form-control input-lg input" id="id_one_time_password" name="one_time_password" type="password" required />
          <div class="error-block">{{ form.one_time_password.errors }}</div>
        </div>


        <button type="submit" name="register"
                class="btn btn-primary btn-lg ">
        Confirm
        </button>

        <p class="text-center">
        Didn't recieve one time password?   <a   style="text-align:center" href="{% url "accounts:register_url" %}"><h4>Resend OTP</h4></a>
        </p>


      </form>
    </div>

    </div>
      {% endblock %}
</div>
    </div> <!-- /container -->

  </div>

  </body>
</html>